//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixMe.Database.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public int Id { get; set; }
        public int DonationRequestId { get; set; }
        public long AmountDonated { get; set; }
        public System.DateTime DonatedOn { get; set; }
        public int DonatedBy { get; set; }
    
        public virtual DonationRequest DonationRequest { get; set; }
        public virtual User User { get; set; }
    }
}
