# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fix Me' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fix Me

  pod 'Alamofire'
  pod 'Material'
  pod 'CircleMenu'
  pod 'IQKeyboardManager'
  pod "TTGSnackbar"
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'
  pod 'DGActivityIndicatorView'
  pod 'GradientProgressBar', '~> 1.0'
  pod "LinearProgressBar"
  
end
